name: デイリータスク
description: 日々のタスクを管理するためのテンプレート
title: "[Daily] "
labels: ["daily", "task"]
body:
  - type: markdown
    attributes:
      value: |
        ## デイリータスク
        優先度はラベルで設定してください。

  - type: textarea
    id: tasks
    attributes:
      label: タスク一覧
      placeholder: |
        - [ ] タスク1
        - [ ] タスク2
        - [ ] タスク3
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: 日付
      placeholder: YYYY-MM-DD
      value: |
        ${{ date }}
    validations:
      required: true