name: プロジェクトタスク
description: プロジェクトごとのタスクを管理するためのテンプレート（子タスク付き）
title: "[Project] "
labels: ["project", "task"]
body:
  - type: markdown
    attributes:
      value: |
        ## プロジェクトタスク
        優先度はラベルで設定してください（priority:high / priority:medium / priority:low）

  - type: input
    id: project_name
    attributes:
      label: プロジェクト名
      placeholder: 例: Webサイトリニューアル
    validations:
      required: true

  - type: textarea
    id: main_tasks
    attributes:
      label: メインタスク
      placeholder: |
        - [ ] タスク1
        - [ ] タスク2
        - [ ] タスク3
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: 子タスク
      placeholder: |
        ## タスク1の子タスク
        - [ ] 子タスク1-1
        - [ ] 子タスク1-2
        
        ## タスク2の子タスク
        - [ ] 子タスク2-1
        - [ ] 子タスク2-2

